### ISSUE TITLE
Merge or consensus tree 

### ISSUE THREAD

**Issue by nansari-pour** [cbg-ethz/SCITE#9]
Hi there,

When I get more than one tree, I am able to find the consensus by running 'consense' in PHYLIP on all .newick trees. However, I am not able to merge or find the consensus for .gv output. I have tried Graphviz (gvpack) but it doesn't seem to work.

Is there a way to merge the mutation trees in .gv format to get the consensus tree?

Also, what is the best tool to visualise the .gv trees?

Thanks

**Comment by jahnka** [comment]
I'm not aware of any consensus tree builder for Graphviz files, but agree it would be a useful function. For visualization I just use Graphviz (on Mac OS).
